set default config values when not defined
Looks tike this was the intention, otherwise eg. the metrics controller
can receive None instead of an empty list, which isn't handled.

    Traceback (most recent call last):
      File "/opt/openmotics/python-develop/gateway/metrics_controller.py", line 533, in _distribute_openmotics
        receiver(metric)
      File "/opt/openmotics/python-develop/gateway/metrics_controller.py", line 309, in receiver
        if not self._needs_upload_to_cloud(metric):
      File "/opt/openmotics/python-develop/gateway/metrics_controller.py", line 277, in _needs_upload_to_cloud
        if metric_type not in metric_types:
    TypeError: argument of type 'NoneType' is not iterable